---
title: "Simple document"
output: github_document
---
```{r}
library(tidyverse)
```

lets import the 'FAS_litters.csv'

```{r}
litters_df = read_csv("./data/FAS_litters.csv")

# clean the name, upper case to lower case...
litters_df 
  janitor::clean_names(litters_df)

```

Import the same dataset using an absolute path 


```{r}
litters_df_abs = read_csv("~/Desktop/data_wrangleing_1/data/FAS_litters.csv")

# clean the name, upper case to lower case...
litters_df_abs =  janitor::clean_names(litters_df)

```

Import pup data

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = read_csv(file = "~/Desktop/data_wrangleing_1/data/FAS_pups.csv")
```

## Look at data

```{r}
litters_df

head(litters_df) # first six rows
tail(litters_df) 
```

you can use 'view'

```{r, eval = FALSE}
view(litters_df) # don't include view in Rmd file 
```

look at a data summary 

```{r}
str(litters_df) # structure of the dataframe

skimr::skim(litters_df)
```


## Options in `read_*`


```{r}
# read csv assume the first rwo is the name 
litters_df = 
  read_csv("data/FAS_litters.csv", 
           skip = 10, col_names = FALSE) # can skip 10 rows
```

look at NA vlaues

```{r,eval = FALSE }
litters_df = 
  read_csv("data/FAS_litters.csv", 
           na = c("NA", 19)) # treating 19 as na vlaues 

```

column types

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_factor()
  )
)
head(litters_data)

```


```{r}
library(tidyverse)
library(readxl)
library(haven)
# read xlsx files
```

import a xlsx file first 


```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

import a SAS file

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


